# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopilot < Formula
  desc "Terminal-based AI coding assistant powered by Google Gemini"
  homepage "https://github.com/JakobAIOdev/GoPilot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.0/gopilot_0.1.0_darwin_amd64.tar.gz"
      sha256 "933719279094f17c2013be21dfce2a53c65f1c9df59e08f04f2e7cdf9e849761"

      define_method(:install) do
        bin.install "gopilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.0/gopilot_0.1.0_darwin_arm64.tar.gz"
      sha256 "76bef3e2b826b8ebe43796cfff4c5efc6723dcd76c19dac6b1ebd219cd8579a0"

      define_method(:install) do
        bin.install "gopilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.0/gopilot_0.1.0_linux_amd64.tar.gz"
      sha256 "9ba36419b1a493294abf55d77ab3e71d02470c1cff4cead04ae64a2557810d2e"
      define_method(:install) do
        bin.install "gopilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.0/gopilot_0.1.0_linux_arm64.tar.gz"
      sha256 "31e048b5f0360f790bf20aa2a3cbd17aecc703f1989125ece2813592d84f6ebd"
      define_method(:install) do
        bin.install "gopilot"
      end
    end
  end

  test do
    system "#{bin}/gopilot", "--version"
  end
end
