# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopilot < Formula
  desc "Terminal-based AI coding assistant powered by Google Gemini"
  homepage "https://github.com/JakobAIOdev/GoPilot"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.1/gopilot_0.1.1_darwin_amd64.tar.gz"
      sha256 "38ea832559b10debc20e2f808ffb59a7629585b32c53ad3214c6f709d62615f3"

      define_method(:install) do
        bin.install "gopilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.1/gopilot_0.1.1_darwin_arm64.tar.gz"
      sha256 "a45e41ff56ea7db3296bfa89585bae3f5751d203a9cfb3929ec7782b24098972"

      define_method(:install) do
        bin.install "gopilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.1/gopilot_0.1.1_linux_amd64.tar.gz"
      sha256 "698ff31dfb27c55e9f4d307f96b7cb66e3241dc8782839af1db5d5c8a104be11"
      define_method(:install) do
        bin.install "gopilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakobAIOdev/GoPilot/releases/download/v0.1.1/gopilot_0.1.1_linux_arm64.tar.gz"
      sha256 "1b21896b629d637a032e7fdc38c5569fecc1b36430d1b9eb72700f854037992c"
      define_method(:install) do
        bin.install "gopilot"
      end
    end
  end

  test do
    system "#{bin}/gopilot", "--version"
  end
end
